sudo: required
addons:
    apt:
        packages:
         - musl
         - musl-dev
         - musl-tools

language: rust

script:
    - rustup default nightly
    - rustup target add x86_64-unknown-linux-musl
    - cargo build --release --target x86_64-unknown-linux-musl
    - docker build .
